### ISSUE TITLE
Syntax portability for creating sequences in bash

### ISSUE THREAD

**Issue by abeyh** [LindenParkesLab/snaplab.github.io#2]
In `docs/amarel/jobs.md`, a trick is used to submit more jobs than the slurm limit. For that, a numerical sequence [0 500 1000 1500] is created like below: 
```bash
for i in {0..1500..500}; do
    ...
```

A more portable syntax to create the sequence would be:
```bash
for i in $(seq 0 500 1500); do
    ...
```

**Comment by lindenmp** [comment]
Good catch. Fixed! Updated the .md doc; see 5e5dc77
